"""
Research Report Generator
"""

from datetime import datetime

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)


class ReportGenerator:

    def generate(
        self,
        filename,
        question,
        answer,
        sources=None,
    ):

        document = SimpleDocTemplate(filename)

        styles = getSampleStyleSheet()

        story = []

        # ------------------------------------------------
        # Title
        # ------------------------------------------------

        story.append(
            Paragraph(
                "AI Research Assistant Report",
                styles["Title"],
            )
        )

        story.append(Spacer(1, 12))

        story.append(
            Paragraph(
                f"<b>Date Generated:</b> {datetime.now().strftime('%d %B %Y, %I:%M %p')}",
                styles["Normal"],
            )
        )

        story.append(Spacer(1, 20))

        # ------------------------------------------------
        # Question
        # ------------------------------------------------

        story.append(
            Paragraph(
                "Research Question",
                styles["Heading1"],
            )
        )

        story.append(
            Paragraph(
                question,
                styles["BodyText"],
            )
        )

        story.append(Spacer(1, 20))

        # ------------------------------------------------
        # Executive Summary
        # ------------------------------------------------

        story.append(
            Paragraph(
                "Executive Summary",
                styles["Heading1"],
            )
        )

        summary = (
            answer[:500] + "..."
            if len(answer) > 500
            else answer
        )

        story.append(
            Paragraph(
                summary.replace("\n", "<br/>"),
                styles["BodyText"],
            )
        )

        story.append(Spacer(1, 20))

        # ------------------------------------------------
        # Detailed Findings
        # ------------------------------------------------

        story.append(
            Paragraph(
                "Detailed Findings",
                styles["Heading1"],
            )
        )

        story.append(
            Paragraph(
                answer.replace("\n", "<br/>"),
                styles["BodyText"],
            )
        )

        story.append(Spacer(1, 20))

        # ------------------------------------------------
        # Sources
        # ------------------------------------------------

        if sources:

            story.append(
                Paragraph(
                    "Sources",
                    styles["Heading1"],
                )
            )

            for source in sources:

                story.append(
                    Paragraph(
                        f"• {source}",
                        styles["BodyText"],
                    )
                )

            story.append(Spacer(1, 20))

        # ------------------------------------------------
        # Footer
        # ------------------------------------------------

        story.append(
            Paragraph(
                "<i>Generated by AI Research Assistant</i>",
                styles["Italic"],
            )
        )

        document.build(story)